spring:
  cloud:
    discovery:
      locator:
        enabled: 'true'
      enabled: 'true'
    consul:
      discovery:
        serviceName: microservice2
        instanceId: microservice2
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  application:
    name: microservice2
  sleuth:
    sampler:
      probability: '0.8'
server:
  port: '8082'
logging:
  config: classpath:logback.xml
