server:
  port: 8888
  
spring:
  main.allow-bean-definition-overriding: true
  application:
    name: config
  profiles:
    active: vault
  cloud.config:
    enabled: false
    server:
      native.search-locations: '@propertiesPath@'
      vault:
        authentication: TOKEN
        token: hvs.Hpg9DWZVSh88DyinPqYfsPJX
        scheme: http
        host: 127.0.0.1
        port: 8200
        backend: secret
        defaultKey: application
        kvVersion: 2
        skipSslValidation: false
        config:
          order: 1
  import: vault://secret/gateway
            

        
      






#spring.application.name=config
#server.port:9101
#spring.cloud.config.server.native.search-locations=@propertiesPath@
####################################################################
#
##ports
#port.gateway=8090
#port.microserviceA=8081
#port.microserviceB=8082
#port.microserviceElk1=42960
#port.microserviceElk2=42961
#port.microserviceVault=8091
#
##url
#zipkin.url=http://localhost:9411
#consul.url=http://localhost:8500
#vault.url=http://localhost:8200
#traefik.url=http://localhost:8080